### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by mousetree** [mousetree/react-seed#1]
Basics:
- [x] Builds for development and production
- [x] Material-UI
- [x] Routing and Sample Pages
- [ ] Redux + devtools
- [ ] Unit Tests
- [x] Continuous Deployment (Travis+Heroku)
- [ ] Querying an API [here](http://jsonplaceholder.typicode.com)

Useful:
- [ ] Authentication [here](https://github.com/auth0/lock), [here](https://github.com/auth0-blog/redux-auth/tree/auth0-lock)
- [ ] Mock backend (json-server)
- [ ] Icons that look decent

Things I want to try:
- [ ] Invariant
- [ ] Redux Saga
- [ ] Progressive Web App
- [ ] Isomorphic app [here](https://github.com/reactjs/react-router-tutorial/tree/master/lessons/13-server-rendering)
- [ ] Flow
- [ ] Yarn
- [ ] Async/Await
- [ ] E2E testing with Nightwatch

Examples to include in .md files:
- [ ] Charts
- [ ] Maps
